FROM python:3-alpine
RUN apk add --update bash netcat-openbsd openssh-keygen build-base && \
    mkdir -p /certs
    
WORKDIR '/app'
COPY ./requirements.txt ./

RUN pip install -r requirements.txt

CMD ["/app/start-dev.sh"]

EXPOSE 5000