FROM python:3-alpine
RUN apk add --update bash netcat-openbsd nodejs nodejs-npm && \
    npm install -g nodemon

WORKDIR '/app'
COPY ./requirements.txt ./

RUN pip install -r requirements.txt

CMD ["/app/start-dev.sh"]